---
- hosts: 
  - "{{ serverhost }}"
  become: yes
  tasks:
   - name: judge whether the update folder exists
     shell: ls {{ serverPath }}update
     ignore_errors: True
     register: result
   - name: mkdir update folder if not exists
     file: path={{ serverPath }}update state=directory
     when: result is failed
   - name: push file to server
     copy: src={{ file }} dest={{ serverPath }}update
   - name: unzip file
     shell: cd {{ serverPath }}update && unzip -o {{ file }}
   - name: copy to the manage
     shell: cd {{ serverPath }}update && rsync -av --exclude {{ file }} * /opt/manage
   - name: backup zip file
     shell: cp {{ serverPath }}update/{{ file }} {{ serverPath }}{{ file }}_{{ nowdata }}
   - name: rm files
     shell: find {{ serverPath }}update/*|xargs rm -rf
   - name: stop services
     shell: cd /opt/manage && sh stop.sh
   - name: wait stop services
     shell: sleep 2
   - name: start services
     shell: cd /opt/manage && sh start.sh
